# Generated by Django 5.1.15 on 2026-05-18 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('single', 'Бір дұрыс жауап'), ('multiple', 'Бірнеше дұрыс жауап'), ('tf', 'Дұрыс / Бұрыс'), ('fill', 'Бос орынды толтыр'), ('match', 'Сәйкестендіру'), ('order', 'Реттеу'), ('short', 'Қысқа ашық жауап')], default='single', max_length=12)),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Жауаптан кейін көрсетіледі')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('situation', models.TextField(help_text='Педагогикалық жағдайдың сипаттамасы')),
                ('questions', models.JSONField(default=list, help_text="['Бұл жағдайда мұғалім не істеуі керек?', ...]")),
                ('expert_analysis', models.TextField(blank=True, help_text='Методист дайындаған эталондық талдау')),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('difficulty', models.CharField(choices=[('easy', 'Жеңіл'), ('medium', 'Орта'), ('hard', 'Күрделі')], default='medium', max_length=8)),
                ('min_words', models.PositiveIntegerField(default=150)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courses.module')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Жоба'), ('graded', 'Бағаланды'), ('failed', 'Қате')], default='draft', max_length=8)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('criteria_scores', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.casestudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('module', 'Модуль тесті'), ('final', 'Финалдық емтихан')], default='module', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = шектеусіз')),
                ('pass_pct', models.PositiveSmallIntegerField(default=70)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30)),
                ('question_count_override', models.PositiveIntegerField(default=0, help_text='0 = барлық сұрақтар; әйтпесе кездейсоқ N таңдалады')),
                ('is_published', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('module', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['course', 'kind'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Жүруде'), ('submitted', 'Тапсырылды'), ('expired', 'Уақыты бітті')], default='in_progress', max_length=16)),
                ('score_pct', models.PositiveSmallIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_max', models.PositiveIntegerField(default=0)),
                ('questions_snapshot', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
